# Site settings
name: Crowd DJ
title: Crowd DJ
description:
url: https://crowddj.github.io/
baseurl: ""
email:
social:
  - title: email
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"
